<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
 
if ( ! function_exists('job_name')){
   function job_name($x){
        switch ($x) {
            // case 'J10' : return 'Breakers, LV Insulated Case >400A (inlcuding trip units)'; break;
            // case 'J11' : return 'Switches, LV (>400A)'; break;
            // case 'J12' : return 'DC power supply'; break;
            // case 'J13' : return 'Battery Charger'; break;
            // case 'J14' : return 'UPS System'; break;
            // case 'J15' : return 'Batteries, Sealed and Vented'; break;
            // case 'J16' : return 'Breakers(Short Circuit Breaker), HV Air'; break;
            // case 'J16' : return 'Breakers(Short Circuit Breaker), HV Vacuum'; break;
            // case 'J16' : return 'Breakers(Short Circuit Breaker), HV Oil'; break;
            // case 'J16' : return 'Breakers(Short Circuit Breaker), HV SF6'; break;
            // case 'J17' : return 'Switches, HV Air (with or without fuse)'; break;
            // case 'J17' : return 'Switches, HV Vacuum (with or without fuse)'; break;
            // case 'J17' : return 'Switches, HV SF6 (with or without fuse)'; break;
            // case 'J19' : return 'Switchgear/Switchboard (including MCC), LV '; break;
            // case 'J20' : return 'Starters (Contactors), fixed mounted, LV'; break;
            // case 'J21' : return 'Starters (Contactors), withdrawable, LV'; break;
            // case 'J24' : return 'Variable Speed Drives VSD, LV'; break;
            // case 'J25' : return 'Softstarters, LV'; break;
            // case 'J4'  : return 'Transformer, Oil-Filled >500 KVA (incl. OLTC)'; break;
            // case 'J40' : return 'Main feeding busbars, LV, External'; break;
            // case 'J42' : return 'Power Factor Correction PFC (Capacitors incl. Reactors), LV'; break;
            // case 'J46' : return 'Starters (Contactors), HV Vacuum'; break;
            // case 'J46' : return 'Starters (Contactors), HV Air'; break;
            // case 'J47' : return 'Variable Speed Drive VSD, HV'; break;
            // case 'J48' : return 'Softstarter, HV'; break;
            // case 'J5'  : return 'Transformer, Oil-Filled >= 5000 KVA (incl. OLTC)'; break;
            // case 'J6'  : return 'Transformer, Dry-Type >500 KVA'; break;
            // case 'J60' : return 'Cable, HV '; break;
            // case 'J61' : return 'Cables, LV'; break;
            // case 'J62' : return 'Overhead power line, HV'; break;
            // case 'J62' : return 'Overhead power line, LV'; break;
            // case 'J7'  : return 'Transformer, Dry-Type >= 5000 KVA'; break;
            // case 'J8'  : return 'Breakers, LV Power >400A (inlcuding trip units)'; break;
            // case 'J9'  : return 'Breakers, LV Molded Case >400A (inlcuding trip units)'; break;

            case 'J1'   : return 'RCD testing'; break;
            case 'J2'   : return 'Portable Tools testing'; break;
            case 'J3'   : return 'Portable RCD testing'; break;
            case 'J4'   : return 'Transformer Oil 500kVA'; break;
            case 'J5'   : return 'Transformer Oil 5000kVA'; break;
            case 'J6'   : return 'Transformer, Dry-Type >500 KVA'; break;
            case 'J7'   : return 'Transformer, Dry-Type >= 5000 KVA'; break;
            case 'J8'   : return 'LV CB Power'; break;
            case 'J9'   : return 'LV CB Molded-Case'; break;
            case 'J10'  : return 'LV CB Insulated-Case'; break;
            case 'J11'  : return 'HV Air Circuit Breaker'; break;
            case 'J12'  : return 'DC power supply'; break;
            case 'J13'  : return 'Battery Charger'; break;
            case 'J14'  : return 'UPS '; break;
            case 'J15'  : return 'Batteries'; break;
            case 'J16'  : return 'HV Circuit Breaker'; break;
            case 'J17'  : return 'HV Switch'; break;
            case 'J18'  : return 'HV Switchgear-Switchboard'; break;
            case 'J19'  : return 'LV Switchgear-Switchboard'; break;
            case 'J20'  : return 'Fixed LV motor starter testing'; break;
            case 'J21'  : return 'MCC drawer testing'; break;
            case 'J22'  : return 'Socket testing'; break;
            case 'J23'  : return 'Electrical room inspection'; break;
            case 'J24'  : return 'LV VFD'; break;
            case 'J25'  : return 'LV Soft Starter'; break;
            case 'J26'  : return ''; break;
            case 'J27'  : return ''; break;
            case 'J28'  : return ''; break;
            case 'J29'  : return 'Lightning protection '; break;
            case 'J30'  : return 'Ground Fault Indication (HRG/LRG/IT)'; break;
            case 'J31'  : return 'Ground system testing'; break;
            case 'J32'  : return 'Conduit and Cable Tray Inspection'; break;
            case 'J33'  : return 'Emergency Lighting'; break;
            case 'J34'  : return 'Junction Box Inspection'; break;
            case 'J35'  : return 'Disconnect-Field Work Switch Inspection'; break;
            case 'J36'  : return 'Cathodic protection for undergorund tanks'; break;
            case 'J37'  : return 'Lighting Fixtures'; break;
            case 'J38'  : return ''; break;
            case 'J39'  : return ''; break;
            case 'J40'  : return 'LV Bus Bar-Bus Duct'; break;
            case 'J41'  : return 'Protective relay'; break;
            case 'J42'  : return 'PFC- Rev D'; break;
            case 'J43'  : return 'Surge Arrester'; break;
            case 'J44'  : return 'PFC (Capacitors incl. Reactors), HV'; break;
            case 'J45'  : return 'Main feeding Busbars Air Insulated HV, External'; break;
            case 'J46'  : return 'Starters (Contactors), HV Vacuum'; break;
            case 'J47'  : return 'Variable Speed Drive VSD, HV'; break;
            case 'J48'  : return 'Softstarter, HV'; break;
            case 'J49'  : return ''; break;
            case 'J50'  : return 'Motor, HV'; break;
            case 'J51'  : return 'Generator HV'; break;
            case 'J52'  : return 'Motor, LV'; break;
            case 'J53'  : return 'Generator LV'; break;
            case 'J54'  : return ''; break;
            case 'J55'  : return ''; break;
            case 'J56'  : return ''; break;
            case 'J57'  : return ''; break;
            case 'J58'  : return ''; break;
            case 'J59'  : return ''; break;
            case 'J60'  : return 'HV Cable'; break;
            case 'J61'  : return 'LV Cable'; break;
            case 'J62'  : return 'Overhead power line, LV'; break;
            case 'J63'  : return ''; break;
            case 'J64'  : return ''; break;
            case 'J65'  : return ''; break;
            case 'J66'  : return ''; break;
            case 'J67'  : return ''; break;
            case 'J68'  : return ''; break;
            case 'J69'  : return ''; break;
            case 'J70'  : return 'Electrical Heaters'; break;
            case 'J71'  : return 'Heat Tracing'; break;
            case 'J72'  : return ''; break;
            case 'J73'  : return ''; break;
            case 'J74'  : return ''; break;
            case 'J75'  : return ''; break;
            case 'J76'  : return ''; break;
            case 'J77'  : return ''; break;
            case 'J78'  : return ''; break;
            case 'J79'  : return ''; break;
            case 'J80'  : return ''; break;
            case 'J81'  : return ''; break;
            case 'J82'  : return ''; break;
            case 'J83'  : return ''; break;
            case 'J84'  : return ''; break;
            case 'J85'  : return ''; break;
            case 'J86'  : return ''; break;
            case 'J87'  : return ''; break;
            case 'J88'  : return ''; break;
            case 'J89'  : return ''; break;
            case 'J90'  : return ''; break;
            case 'J91'  : return ''; break;
            case 'J92'  : return ''; break;
            case 'J93'  : return ''; break;
            case 'J94'  : return ''; break;
            case 'J95'  : return ''; break;
            case 'J96'  : return ''; break;
            case 'J97'  : return ''; break;
            case 'J98'  : return ''; break;
            case 'J99'  : return ''; break;
            case 'J101' : return 'Electrical Studies'; break;
            case 'J102' : return ''; break;
            case 'J103' : return ''; break;
            case 'J104' : return ''; break;
            case 'J105' : return ''; break;
            case 'J106' : return 'Accountability'; break;
            case 'J107' : return 'Training, Qualification and Authorization'; break;


            default: return "-";  break;
        }
    }
}